//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Views.Persistence
{
	/// <summary>Static class for (extension) methods for fetching and projecting instances of Views.DtoClasses.RoleView from the entity model.</summary>
	public static partial class RoleViewPersistence
	{
		private static readonly System.Linq.Expressions.Expression<Func<Demo.EntityClasses.RoleEntity, Views.DtoClasses.RoleView>> _projectorExpression = CreateProjectionFunc();
		private static readonly Func<Demo.EntityClasses.RoleEntity, Views.DtoClasses.RoleView> _compiledProjector = CreateProjectionFunc().Compile();
	
		/// <summary>Empty static ctor for triggering initialization of static members in a thread-safe manner</summary>
		static RoleViewPersistence() { }
	
		/// <summary>Extension method which produces a projection to Views.DtoClasses.RoleView which instances are projected from the 
		/// results of the specified baseQuery, which returns Demo.EntityClasses.RoleEntity instances, the root entity of the derived element returned by this query.</summary>
		/// <param name="baseQuery">The base query to project the derived element instances from.</param>
		/// <returns>IQueryable to retrieve Views.DtoClasses.RoleView instances</returns>
		public static IQueryable<Views.DtoClasses.RoleView> ProjectToRoleView(this IQueryable<Demo.EntityClasses.RoleEntity> baseQuery)
		{
			return baseQuery.Select(_projectorExpression);
		}
		
		/// <summary>Extension method which produces a projection to Views.DtoClasses.RoleView which instances are projected from the
		/// Demo.EntityClasses.RoleEntity entity instance specified, the root entity of the derived element returned by this method.</summary>
		/// <param name="entity">The entity to project from.</param>
		/// <returns>Demo.EntityClasses.RoleEntity instance created from the specified entity instance</returns>
		public static Views.DtoClasses.RoleView ProjectToRoleView(this Demo.EntityClasses.RoleEntity entity)
		{
			return _compiledProjector(entity);
		}
		
		private static System.Linq.Expressions.Expression<Func<Demo.EntityClasses.RoleEntity, Views.DtoClasses.RoleView>> CreateProjectionFunc()
		{
			return p__0 => new Views.DtoClasses.RoleView()
			{
				NameArabic = p__0.NameArabic,
				UserRoles = p__0.UserRoles.Select(p__1 => new Views.DtoClasses.RoleViewTypes.UserRole()
				{
					Id = p__1.Id,
					IsActive = p__1.IsActive,
					RoleId = p__1.RoleId,
					UserId = p__1.UserId,
				}).ToList(),
	// __LLBLGENPRO_USER_CODE_REGION_START ProjectionRegion_RoleView 
	// __LLBLGENPRO_USER_CODE_REGION_END 
			};
		}
	}
}

