//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Views.Persistence
{
	/// <summary>Static class for (extension) methods for fetching and projecting instances of Views.DtoClasses.UserView from the entity model.</summary>
	public static partial class UserViewPersistence
	{
		private static readonly System.Linq.Expressions.Expression<Func<Demo.EntityClasses.UserEntity, Views.DtoClasses.UserView>> _projectorExpression = CreateProjectionFunc();
		private static readonly Func<Demo.EntityClasses.UserEntity, Views.DtoClasses.UserView> _compiledProjector = CreateProjectionFunc().Compile();
	
		/// <summary>Empty static ctor for triggering initialization of static members in a thread-safe manner</summary>
		static UserViewPersistence() { }
	
		/// <summary>Extension method which produces a projection to Views.DtoClasses.UserView which instances are projected from the 
		/// results of the specified baseQuery, which returns Demo.EntityClasses.UserEntity instances, the root entity of the derived element returned by this query.</summary>
		/// <param name="baseQuery">The base query to project the derived element instances from.</param>
		/// <returns>IQueryable to retrieve Views.DtoClasses.UserView instances</returns>
		public static IQueryable<Views.DtoClasses.UserView> ProjectToUserView(this IQueryable<Demo.EntityClasses.UserEntity> baseQuery)
		{
			return baseQuery.Select(_projectorExpression);
		}
		
		/// <summary>Extension method which produces a projection to Views.DtoClasses.UserView which instances are projected from the
		/// Demo.EntityClasses.UserEntity entity instance specified, the root entity of the derived element returned by this method.</summary>
		/// <param name="entity">The entity to project from.</param>
		/// <returns>Demo.EntityClasses.UserEntity instance created from the specified entity instance</returns>
		public static Views.DtoClasses.UserView ProjectToUserView(this Demo.EntityClasses.UserEntity entity)
		{
			return _compiledProjector(entity);
		}
		
		private static System.Linq.Expressions.Expression<Func<Demo.EntityClasses.UserEntity, Views.DtoClasses.UserView>> CreateProjectionFunc()
		{
			return p__0 => new Views.DtoClasses.UserView()
			{
				Email = p__0.Email,
				Id = p__0.Id,
				IsActive = p__0.IsActive,
				Name = p__0.Name,
				NationalId = p__0.NationalId,
				UserRoles = p__0.UserRoles.Select(p__1 => new Views.DtoClasses.UserViewTypes.UserRole()
				{
					Id = p__1.Id,
					IsActive = p__1.IsActive,
					Role = new Views.DtoClasses.UserViewTypes.UserRoleTypes.Role()
					{
						Id = p__1.Role.Id,
						IsActive = p__1.Role.IsActive,
						NameArabic = p__1.Role.NameArabic,
						NameEnglish = p__1.Role.NameEnglish,
					},
					RoleId = p__1.RoleId,
					UserId = p__1.UserId,
				}).ToList(),
	// __LLBLGENPRO_USER_CODE_REGION_START ProjectionRegion_UserView 
	// __LLBLGENPRO_USER_CODE_REGION_END 
			};
		}
	}
}

