//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using Demo.FactoryClasses;
using Demo.RelationClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Demo.HelperClasses
{
	/// <summary>Singleton implementation of the ModelInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	public static class ModelInfoProviderSingleton
	{
		private static readonly IModelInfoProvider _providerInstance = new ModelInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static ModelInfoProviderSingleton()	{ }

		/// <summary>Gets the singleton instance of the ModelInfoProviderCore</summary>
		/// <returns>Instance of the FieldInfoProvider.</returns>
		public static IModelInfoProvider GetInstance()
		{
			return _providerInstance;
		}
	}

	/// <summary>Actual implementation of the ModelInfoProvider.</summary>
	internal class ModelInfoProviderCore : ModelInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="ModelInfoProviderCore"/> class.</summary>
		internal ModelInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores.</summary>
		private void Init()
		{
			this.InitClass();
			InitRoleEntityInfo();
			InitUserEntityInfo();
			InitUserRoleEntityInfo();
			this.BuildInternalStructures();
		}

		/// <summary>Inits RoleEntity's info objects</summary>
		private void InitRoleEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(RoleFieldIndex), "RoleEntity");
			this.AddElementFieldInfo("RoleEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)RoleFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("RoleEntity", "IsActive", typeof(System.Boolean), false, false, false, false,  (int)RoleFieldIndex.IsActive, 0, 0, 0);
			this.AddElementFieldInfo("RoleEntity", "NameArabic", typeof(System.String), false, false, false, true,  (int)RoleFieldIndex.NameArabic, 250, 0, 0);
			this.AddElementFieldInfo("RoleEntity", "NameEnglish", typeof(System.String), false, false, false, true,  (int)RoleFieldIndex.NameEnglish, 250, 0, 0);
		}

		/// <summary>Inits UserEntity's info objects</summary>
		private void InitUserEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(UserFieldIndex), "UserEntity");
			this.AddElementFieldInfo("UserEntity", "CreatedByUserId", typeof(Nullable<System.Int32>), false, true, false, true,  (int)UserFieldIndex.CreatedByUserId, 0, 0, 10);
			this.AddElementFieldInfo("UserEntity", "DateCreated", typeof(System.DateTime), false, false, false, false,  (int)UserFieldIndex.DateCreated, 0, 0, 0);
			this.AddElementFieldInfo("UserEntity", "Email", typeof(System.String), false, false, false, true,  (int)UserFieldIndex.Email, 250, 0, 0);
			this.AddElementFieldInfo("UserEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)UserFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("UserEntity", "IsActive", typeof(System.Boolean), false, false, false, false,  (int)UserFieldIndex.IsActive, 0, 0, 0);
			this.AddElementFieldInfo("UserEntity", "LastModified", typeof(System.DateTime), false, false, false, false,  (int)UserFieldIndex.LastModified, 0, 0, 0);
			this.AddElementFieldInfo("UserEntity", "LastModifiedByUserId", typeof(Nullable<System.Int32>), false, true, false, true,  (int)UserFieldIndex.LastModifiedByUserId, 0, 0, 10);
			this.AddElementFieldInfo("UserEntity", "Name", typeof(System.String), false, false, false, false,  (int)UserFieldIndex.Name, 250, 0, 0);
			this.AddElementFieldInfo("UserEntity", "NationalId", typeof(System.String), false, false, false, true,  (int)UserFieldIndex.NationalId, 14, 0, 0);
		}

		/// <summary>Inits UserRoleEntity's info objects</summary>
		private void InitUserRoleEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(UserRoleFieldIndex), "UserRoleEntity");
			this.AddElementFieldInfo("UserRoleEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)UserRoleFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("UserRoleEntity", "IsActive", typeof(System.Boolean), false, false, false, false,  (int)UserRoleFieldIndex.IsActive, 0, 0, 0);
			this.AddElementFieldInfo("UserRoleEntity", "RoleId", typeof(System.Int32), false, true, false, false,  (int)UserRoleFieldIndex.RoleId, 0, 0, 10);
			this.AddElementFieldInfo("UserRoleEntity", "UserId", typeof(System.Int32), false, true, false, false,  (int)UserRoleFieldIndex.UserId, 0, 0, 10);
		}
	}
}