//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace Views.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'Role'.</summary>
	[Serializable]
	[DataContract]
	public partial class RoleView
	{
		/// <summary>Gets or sets the NameArabic field. Derived from Entity Model Field 'Role.NameArabic'</summary>
		[DataMember]
		public System.String NameArabic { get; set; }
		/// <summary>Gets or sets the UserRoles field. </summary>
		[DataMember]
		public List<RoleViewTypes.UserRole> UserRoles { get; set; }
	}

	namespace RoleViewTypes
	{
		/// <summary> DTO class which is derived from the entity 'UserRole (UserRoles)'.</summary>
		[Serializable]
		[DataContract]
		public partial class UserRole
		{
			/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'UserRole.Id'</summary>
			[DataMember]
			public System.Int32 Id { get; set; }
			/// <summary>Gets or sets the IsActive field. Derived from Entity Model Field 'UserRole.IsActive'</summary>
			[DataMember]
			public System.Boolean IsActive { get; set; }
			/// <summary>Gets or sets the RoleId field. Derived from Entity Model Field 'UserRole.RoleId (FK)'</summary>
			[DataMember]
			public System.Int32 RoleId { get; set; }
			/// <summary>Gets or sets the UserId field. Derived from Entity Model Field 'UserRole.UserId (FK)'</summary>
			[DataMember]
			public System.Int32 UserId { get; set; }
		}
	}

}




